function Info = PtCl_filtering(Voxel_Points,Info,Tree_Section)             

    bin_big = Voxel_Points.VoxelSize >= 1;
    switch Info.setup
        case 'interface'
            bin_1 = bin_viewer(Voxel_Points(bin_big,:));
        case 'fixed'
            bin_1 = binning_func(Voxel_Points(bin_big,:),Info,Tree_Section);
    end	

    bin_big(bin_big) = bin_1;
    
    switch Tree_Section
        case 'stem'
            Info.bin_Stems = bin_big;
        case 'crown'
            Info.bin_Crown = bin_big;
    end

    function  bin = bin_viewer(Cloud)

            Cloud.Intensity     = Cloud.Intensity./max(Cloud.Intensity);
            Cloud.Easting       = Cloud.Easting-min(Cloud.Easting);
            Cloud.Northing      = Cloud.Northing-min(Cloud.Northing);
            

            viewvec = [-30 30];

            scrsz = get(0,'ScreenSize');

            width = floor(0.8 * scrsz(3));
            height = floor(0.8 .* scrsz(4));
            left = 1 + floor((scrsz(3) - width)/2);
            bottom = 1 + floor((scrsz(4) - height)/2);

            Colors = rgb_colors('no');

            color1 = 'k';
            color2 = Colors.firebrick;

            hMainFigure    =   figure('Color','w','Position',[left bottom width height],...       % the main GUI figure
                    'HandleVisibility','callback', ...
                    'Name', 'Point Cloud Filtering', ...
                    'NumberTitle','off');

            hPlotAxes      =   axes(...
                    'Parent', hMainFigure, ...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.1 0.6 0.8],'FontSize',10,'FontName','calibri light');

            axis(hPlotAxes,'image');

            set(hPlotAxes,'view',viewvec);

            hp1 = uipanel('Parent', hMainFigure,'Title','Commands','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .01 .24 .14]);

            hp2 = uipanel('Parent', hMainFigure,'Title','Values','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .16 .24 .04]);

            hp3 = uipanel('Parent', hMainFigure,'Title','Threshold','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .21 .24 .78]);

            %% Easting Threshold
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.95 0.29 0.04],...
                    'String','Easting [m]:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');
            switch Tree_Section
                case 'stem'
                    editeastl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.95 0.25 0.04],...
                            'String',num2str(Info.stem_Easting(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editeastu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.95 0.25 0.04],...
                            'String',num2str(Info.stem_Easting(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
                case 'crown'
                    editeastl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.95 0.25 0.04],...
                            'String',num2str(Info.crown_Easting(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editeastu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.95 0.25 0.04],...
                            'String',num2str(Info.crown_Easting(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
            end

            %% Northing Threshold
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.9 0.29 0.04],...
                    'String','Northing [m]:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');
                
            switch Tree_Section
                case 'stem'
                    editnorthl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.9 0.25 0.04],...
                            'String',num2str(Info.stem_Northing(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editnorthu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.9 0.25 0.04],...
                            'String',num2str(Info.stem_Northing(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
                case 'crown'
                    editnorthl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.9 0.25 0.04],...
                            'String',num2str(Info.crown_Northing(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editnorthu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.9 0.25 0.04],...
                            'String',num2str(Info.crown_Northing(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');                    
            end
                
            %% Voxel Size
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.85 0.29 0.04],...
                    'String','Voxel Size:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editvoxell = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.35 0.85 0.25 0.04],...
                    'String',num2str(Info.VoxelSize(1)),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editvoxelu = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.7 0.85 0.25 0.04],...
                    'String',num2str(Info.VoxelSize(2)),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');            
            
            %% Height Threshold
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.7 0.29 0.04],...
                    'String','Height [m]:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');
                
            switch Tree_Section
                case 'stem'            
                    edithl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.7 0.25 0.04],...
                            'String',num2str(Info.stem_height(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    edithu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.7 0.25 0.04],...
                            'String',num2str(Info.stem_height(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
                case 'crown'
                    edithl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.7 0.25 0.04],...
                            'String',num2str(Info.crown_height(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    edithu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.7 0.25 0.04],...
                            'String',num2str(Info.crown_height(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');                    
            end

            histh      =   axes(...
                    'Parent', hp3, ...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.55 0.85 0.14],'FontSize',6,'FontName','calibri light');

            %% Intensity Threshold
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.45 0.29 0.05],...
                    'String','Intensity [0-1]:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');
                
            switch Tree_Section
                case 'stem'
                    editil = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.45 0.25 0.05],...
                            'String',num2str(Info.stem_Intensity(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editiu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.45 0.25 0.05],...
                            'String',num2str(Info.stem_Intensity(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
                case 'crown'
                    editil = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.45 0.25 0.05],...
                            'String',num2str(Info.crown_Intensity(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editiu = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.45 0.25 0.05],...
                            'String',num2str(Info.crown_Intensity(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');
            end

            histi      =   axes(...
                    'Parent', hp3, ...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.3 0.85 0.14],'FontSize',6,'FontName','calibri light');

            %% Return Number Threshold
            uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.2 0.29 0.05],...
                    'String','RNNR mod(11):',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');
                
            switch Tree_Section
                case 'stem'
                    editrnnrl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.2 0.25 0.05],...
                            'String',num2str(Info.stem_RNNR(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editrnnru = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.2 0.25 0.05],...
                            'String',num2str(Info.stem_RNNR(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');                    
                case 'crown'
                    editrnnrl = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.35 0.2 0.25 0.05],...
                            'String',num2str(Info.crown_RNNR(1)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    editrnnru = uicontrol(...
                            'Parent', hp3, ...
                            'Units','normalized',...
                            'Style', 'edit', ...
                            'Position', [0.7 0.2 0.25 0.05],...
                            'String',num2str(Info.crown_RNNR(2)),...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');                      
            end


            histrnnr      =   axes(...
                    'Parent', hp3, ...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.05 0.85 0.14],'FontSize',6,'FontName','calibri light');

            
            %% Button:
            returnbutton  =   uicontrol(...
                    'Parent', hp1, ...
                    'Units','normalized',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.05 0.9 0.425],...
                    'String','Print & Close','FontSize',8,'BackgroundColor','white',...
                    'Style','pushbutton','Callback', @ReturnBin);

            plotbutton  =   uicontrol(...
                    'Parent', hp1, ...
                    'Units','normalized',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.525 0.9 0.425],...
                    'String','Plot','FontSize',8,'BackgroundColor','white',...
                    'Style','pushbutton','Callback', @PlotCloud);

            UpdateThreshold;
            PlotCloud;
            uiwait(hMainFigure)

            function UpdateThreshold(arg1, arg2)
                    %% Get Values
                    val1 = get(edithl, 'String');
                    val2 = get(edithu, 'String');
                    val3 = get(editil, 'String');
                    val4 = get(editiu, 'String');
                    val5 = get(editrnnrl, 'String');
                    val6 = get(editrnnru, 'String');
                    val7 = get(editeastl, 'String');
                    val8 = get(editeastu, 'String');
                    val9 = get(editnorthl, 'String');
                    val10 = get(editnorthu, 'String');
                    val11 = get(editvoxell, 'String');
                    val12 = get(editvoxelu, 'String');

               
                    bin  =   Cloud.AboveDTM >= str2double(val1) & Cloud.AboveDTM <= str2double(val2) &...
                             Cloud.Intensity >= str2double(val3) & Cloud.Intensity <= str2double(val4) &...
                             Cloud.RNNR >= str2double(val5) & Cloud.RNNR <= str2double(val6) &...
                             Cloud.Easting >= str2double(val7) & Cloud.Easting <= str2double(val8) &...
                             Cloud.Northing >= str2double(val9) & Cloud.Northing <= str2double(val10) &...
                             Cloud.VoxelSize >= str2double(val11) & Cloud.VoxelSize <= str2double(val12);
                            

                    amount_total    = num2str(size(bin,1));
                    amount_bin      = num2str(sum(bin));


                    %% Amount of Points
                    uicontrol(...
                            'Parent', hp2, ...
                            'Units','normalized',...
                            'HorizontalAlignment','left',...
                            'HandleVisibility','callback', ...
                            'Position',[0.05 0.05 0.9 0.9],...
                            'String',[amount_bin,' Points of ',amount_total,' selected'],...
                            'Style','text',...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    %% Update Histogramms
                    histogram(histh,Cloud.AboveDTM(bin),50,'FaceColor',color2,'EdgeColor',color1)
                    histogram(histi,Cloud.Intensity(bin),50,'FaceColor',color2,'EdgeColor',color1)
                    histogram(histrnnr,mod(Cloud.RNNR(bin),11),50,'FaceColor',color2,'EdgeColor',color1)
%                     histogram(histdeg,mod(Cloud.Degree(bin),11),50,'FaceColor',color2,'EdgeColor',color1)
                    
            end

            function PlotCloud(arg1, arg2)

                    UpdateThreshold;

                    %% Get Values
                    val1 = get(edithl, 'String');
                    val2 = get(edithu, 'String');
                    val3 = get(editil, 'String');
                    val4 = get(editiu, 'String');
                    val5 = get(editrnnrl, 'String');
                    val6 = get(editrnnru, 'String');
                    val7 = get(editeastl, 'String');
                    val8 = get(editeastu, 'String');
                    val9 = get(editnorthl, 'String');
                    val10 = get(editnorthu, 'String');
                    val11 = get(editvoxell, 'String');
                    val12 = get(editvoxelu, 'String');

               
                    bin  =   Cloud.AboveDTM >= str2double(val1) & Cloud.AboveDTM <= str2double(val2) &...
                             Cloud.Intensity >= str2double(val3) & Cloud.Intensity <= str2double(val4) &...
                             Cloud.RNNR >= str2double(val5) & Cloud.RNNR <= str2double(val6) &...
                             Cloud.Easting >= str2double(val7) & Cloud.Easting <= str2double(val8) &...
                             Cloud.Northing >= str2double(val9) & Cloud.Northing <= str2double(val10) &...
                             Cloud.VoxelSize >= str2double(val11) & Cloud.VoxelSize <= str2double(val12);
                    
                    viewvec = get(hPlotAxes, 'view');

                    scatter3(hPlotAxes,Cloud.Easting(bin),Cloud.Northing(bin),Cloud.AboveSea(bin),1,Cloud.AboveDTM(bin),'.')
                        axis(hPlotAxes,'image');
                        colormap(hPlotAxes,'jet')
                        xlabel(hPlotAxes,'Easting [m]')
                        ylabel(hPlotAxes,'Northing [m]')
                        zlabel(hPlotAxes,'Height [m]')


                    set(hPlotAxes,'view',viewvec,'FontName','calibri light','FontSize',8);

            end

            function ReturnBin(arg1, arg2)
                    %% Get Values
                    val1 = get(edithl, 'String');
                    val2 = get(edithu, 'String');
                    val3 = get(editil, 'String');
                    val4 = get(editiu, 'String');
                    val5 = get(editrnnrl, 'String');
                    val6 = get(editrnnru, 'String');
                    val7 = get(editeastl, 'String');
                    val8 = get(editeastu, 'String');
                    val9 = get(editnorthl, 'String');
                    val10 = get(editnorthu, 'String');
                    val11 = get(editvoxell, 'String');
                    val12 = get(editvoxelu, 'String');

                    
                    bin  =   Cloud.AboveDTM >= str2double(val1) & Cloud.AboveDTM <= str2double(val2) &...
                            Cloud.Intensity >= str2double(val3) & Cloud.Intensity <= str2double(val4) &...
                            Cloud.RNNR >= str2double(val5) & Cloud.RNNR <= str2double(val6) &...
                            Cloud.Easting >= str2double(val7) & Cloud.Easting <= str2double(val8) &...
                            Cloud.Northing >= str2double(val9) & Cloud.Northing <= str2double(val10) &...
                            Cloud.VoxelSize >= str2double(val11) & Cloud.VoxelSize <= str2double(val12);

                    switch Tree_Section
                        case 'stem'
                            Info.stem_Easting       = [str2double(val7),str2double(val8)];
                            Info.stem_Northing      = [str2double(val9),str2double(val10)];
                            Info.stem_height        = [str2double(val1),str2double(val2)];
                            Info.stem_Intensity     = [str2double(val3),str2double(val4)];
                            Info.stem_RNNR          = [str2double(val5),str2double(val6)];
                            Info.stem_Voxel         = [str2double(val11),str2double(val12)];
                            
                        case 'crown'
                            Info.crown_Easting      = [str2double(val7),str2double(val8)];
                            Info.crown_Northing     = [str2double(val9),str2double(val10)];
                            Info.crown_height       = [str2double(val1),str2double(val2)];
                            Info.crown_Intensity    = [str2double(val3),str2double(val4)];
                            Info.crown_RNNR         = [str2double(val5),str2double(val6)];
                            Info.crown_Voxel        = [str2double(val11),str2double(val12)];
                    end                        
                        
                        
                    close(hMainFigure)

            end

    end

    function bin_1 = binning_func(Cloud,Info,Treepart)

        Cloud.Easting   = Cloud.Easting - min(Cloud.Easting);
        Cloud.Northing  = Cloud.Northing - min(Cloud.Northing);
        Cloud.Intensity = Cloud.Intensity ./ max(Cloud.Intensity);

        switch Treepart
            case 'stem'
                bin_1 = Cloud.AboveDTM >= Info.stem_height(1) & Cloud.AboveDTM <= Info.stem_height(2) &...
                        Cloud.Intensity >= Info.stem_Intensity(1) & Cloud.Intensity <= Info.stem_Intensity(2) &...
                        Cloud.RNNR >= Info.stem_RNNR(1) & Cloud.RNNR <= Info.stem_RNNR(2) &...
                        Cloud.Easting >= Info.stem_Easting(1) & Cloud.Easting <= Info.stem_Easting(2) &...
                        Cloud.Northing >= Info.stem_Northing(1) & Cloud.Northing <= Info.stem_Northing(2) &...
                        Cloud.VoxelSize >= Info.VoxelSize(1) & Cloud.VoxelSize <= Info.VoxelSize(2);
                    
            case 'crown'
                bin_1 = Cloud.AboveDTM >= Info.crown_height(1) & Cloud.AboveDTM <= Info.crown_height(2) &...
                        Cloud.Intensity >= Info.crown_Intensity(1) & Cloud.Intensity <= Info.crown_Intensity(2) &...
                        Cloud.RNNR >= Info.crown_RNNR(1) & Cloud.RNNR <= Info.crown_RNNR(2) &...
                        Cloud.Easting >= Info.crown_Easting(1) & Cloud.Easting <= Info.crown_Easting(2) &...
                        Cloud.Northing >= Info.crown_Northing(1) & Cloud.Northing <= Info.crown_Northing(2) &...
                        Cloud.VoxelSize >= Info.VoxelSize(1) & Cloud.VoxelSize <= Info.VoxelSize(2);  
                    
        end
    end



end