function [Voxel_Points,Info] = trunk_clustering(Voxel_Points,Info)
%%
%
%
%
%

    switch Info.setup
        case 'interface'
            Voxel_Points = graph_viewer(Voxel_Points,Info.bin_Stems);
        case 'fixed'
            [Voxel_Points.Cluster_Nr,Voxel_Points.Cluster_Size] = ...
                        stem_detection(Voxel_Points,Info.bin_Stems,Info);
    end
    
    
    
    function Cloud = graph_viewer(Cloud,bin_1)
            Cloud = Cloud;

            Cloud.Cluster_Nr(:)   = 0;
            Cloud.Cluster_Size(:) = 0;

            viewvec = [-30 30];

            scrsz = get(0,'ScreenSize');

            width = floor(0.8 * scrsz(3));
            height = floor(0.8 .* scrsz(4));
            left = 1 + floor((scrsz(3) - width)/2);
            bottom = 1 + floor((scrsz(4) - height)/2);

            color1 = 'k';

            hMainFigure    =   figure('Color','w','Position',[left bottom width height],...       % the main GUI figure
                    'HandleVisibility','callback', ...
                    'Name', mfilename, ...
                    'NumberTitle','off');

            hPlotAxes      =   axes(...         % the axes for plotting selected plot
                    'Parent', hMainFigure, ...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.1 0.6 0.8],'FontSize',10,'FontName','calibri light');

            axis(hPlotAxes,'image');

            set(hPlotAxes,'view',viewvec);

            hp1 = uipanel('Parent', hMainFigure,'Title','Commands','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .01 .24 .14]);

            hp2 = uipanel('Parent', hMainFigure,'Title','Stats','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .16 .24 .34]);

            hp3 = uipanel('Parent', hMainFigure,'Title','Variables','ForegroundColor',color1,'FontSize',10,'FontWeight','bold',...
                    'BackgroundColor','white',...
                    'Position',[.75 .51 .24 .48]);

            %% max Distance
            uicontrol(...    % text
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.85 0.2 0.05],...
                    'String','Max Distance [m]:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editd = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.25 0.85 0.1 0.05],...
                    'String',num2str(Info.trunk_max_edgeweight),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');


            %% X -Factor
            uicontrol(...    % text
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.65 0.2 0.05],...
                    'String','X-Factor:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editx = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.25 0.65 0.1 0.05],...
                    'String',num2str(Info.trunk_weights(1)),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');


            %% Y -Factor
            uicontrol(...    % text
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.45 0.2 0.05],...
                    'String','Y-Factor:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            edity = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.25 0.45 0.1 0.05],...
                    'String',num2str(Info.trunk_weights(2)),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            %% Z -Factor
            uicontrol(...    % text
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.25 0.2 0.05],...
                    'String','Z-Factor:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editz = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.25 0.25 0.1 0.05],...
                    'String',num2str(Info.trunk_weights(3)),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            %% ClusterSize
            uicontrol(...    % text
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'HorizontalAlignment','left',...
                    'HandleVisibility','callback', ...
                    'Position',[0.05 0.05 0.2 0.05],...
                    'String','Min ClusterSize:',...
                    'Style','text',...
                    'FontSize',10,'FontName','calibri light',...
                    'FontWeight','bold',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            editc = uicontrol(...
                    'Parent', hp3, ...
                    'Units','normalized',...
                    'Style', 'edit', ...
                    'Position', [0.25 0.05 0.1 0.05],...
                    'String',num2str(Info.trunk_min_cluster),...
                    'FontSize',10,'FontName','calibri light',...
                    'ForegroundColor',color1,'BackgroundColor','white');

            %% Button
            returnbutton  =   uicontrol(...    % button
                    'Parent', hp1, ...
                    'Units','normalized',...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.1 0.8 0.375],...
                    'String','Print & Close','FontSize',8,'BackgroundColor','white',...
                    'Style','pushbutton','Callback', @ReturnCloud);

            plotbutton  =   uicontrol(...    % button
                    'Parent', hp1, ...
                    'Units','normalized',...
                    'HandleVisibility','callback', ...
                    'Position',[0.1 0.51 0.8 0.375],...
                    'String','Run','FontSize',8,'BackgroundColor','white',...
                    'Style','pushbutton','Callback', @stemdetection);

            PlotStem;
            Update_Stem_Values;
            uiwait(hMainFigure)

            function Update_Stem_Values(arg1, arg2)
                    %% Get Values
                    amount_total    = size(unique(Cloud.Cluster_Nr),1);


                    %% First Threshold
                    uicontrol(...    % text
                            'Parent', hp2, ...
                            'Units','normalized',...
                            'HorizontalAlignment','left',...
                            'HandleVisibility','callback', ...
                            'Position',[0.05 0.85 0.9 0.09],...
                            'String',[num2str(amount_total-1),' Stems detected.'],...
                            'Style','text',...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    %% Second Threshold
                    uicontrol(...    % text
                            'Parent', hp2, ...
                            'Units','normalized',...
                            'HorizontalAlignment','left',...
                            'HandleVisibility','callback', ...
                            'Position',[0.05 0.75 0.9 0.09],...
                            'String',['...: '],...
                            'Style','text',...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    %% Third Threshold
                    uicontrol(...    % text
                            'Parent', hp2, ...
                            'Units','normalized',...
                            'HorizontalAlignment','left',...
                            'HandleVisibility','callback', ...
                            'Position',[0.05 0.65 0.9 0.09],...
                            'String',['...: '],...
                            'Style','text',...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');

                    %% Amount of Points
                    uicontrol(...    % text
                            'Parent', hp2, ...
                            'Units','normalized',...
                            'HorizontalAlignment','left',...
                            'HandleVisibility','callback', ...
                            'Position',[0.05 0.55 0.9 0.09],...
                            'String',['...: '],...
                            'Style','text',...
                            'FontSize',10,'FontName','calibri light',...
                            'ForegroundColor',color1,'BackgroundColor','white');


            end

            function stemdetection(arg1,arg2)

                    max_d       = str2double(get(editd, 'String'));
                    d_weight(1) = str2double(get(editx, 'String'));
                    d_weight(2) = str2double(get(edity, 'String'));
                    d_weight(3) = str2double(get(editz, 'String'));
                    cluster_s   = str2double(get(editc, 'String'));

                    in = Cloud(bin_1,:);

                    [in.Cluster_Nr,in.Cluster_Size] = stemdetectiongraph(in,max_d,d_weight);

                    in.Cluster_Size(in.Cluster_Size <= cluster_s)   = 0;
                    in.Cluster_Nr(in.Cluster_Size <= cluster_s)     = 0;

                    Cloud(bin_1,:) = in;

                    PlotStem;
                    Update_Stem_Values;
                    
                function [Cluster_Nr,Cluster_Size] = stemdetectiongraph(in,max_d,d_weights)
                    
                    
                    G = graph_creation(in, max_d, d_weights);
                    [comp,compsize]    = conncomp(G);
                    comp(2,:) = compsize(1,comp(1,:));

                    Cluster_Nr   =   comp(1,:)';
                    Cluster_Size =   comp(2,:)';   
                    
                    function G = graph_creation(cloud, edge_distance, d_weights) 

                        DT      = delaunayTriangulation([cloud.Easting,cloud.Northing,cloud.AboveSea]);
                        E       = edges(DT);

                        X       = [cloud.Easting(E(:,1)).*d_weights(1),cloud.Northing(E(:,1)).*d_weights(2),cloud.AboveSea(E(:,1)).*d_weights(3)];
                        Y       = [cloud.Easting(E(:,2)).*d_weights(1),cloud.Northing(E(:,2)).*d_weights(2),cloud.AboveSea(E(:,2)).*d_weights(3)];    
                        D       = X-Y;
                        E(:,3)  = sqrt(D(:,1).^2 + D(:,2).^2 + D(:,3).^2);

                        E(E(:,3)> edge_distance,:) = [];

                        G = graph(E(:,1),E(:,2),E(:,3),size(cloud,1));

                    end
                    
                end

            end

            function PlotStem(arg1,arg2)


                    viewvec = get(hPlotAxes, 'view');

                    scatter3(hPlotAxes,Cloud.Easting(bin_1),Cloud.Northing(bin_1),Cloud.AboveSea(bin_1),1,Cloud.Cluster_Nr(bin_1),'.')
                    axis(hPlotAxes,'image');
                    colormap(hPlotAxes,'lines')


                    set(hPlotAxes,'view',viewvec,'FontName','calibri light','FontSize',8);
            end

            function ReturnCloud(arg1,arg2)
                    Info.trunk_max_edgeweight = str2double(get(editd, 'String'));
                    
                    d_weight(1) = str2double(get(editx, 'String'));
                    d_weight(2) = str2double(get(edity, 'String'));
                    d_weight(3) = str2double(get(editz, 'String'));  
                    
                    Info.trunk_weights = d_weight;
                    
                    Info.trunk_min_cluster   = str2double(get(editc, 'String'));
                    
                    close(hMainFigure)
            end


    end

    function [Cluster_Nr,Cluster_Size] = stem_detection(Cloud,bin,Info)

        Cloud.Cluster_Nr(:)     = 0;
        Cloud.Cluster_Size(:)   = 0;

        max_d                   = Info.trunk_max_edgeweight;
        d_weight                = Info.trunk_weights;
        cluster_s               = Info.trunk_min_cluster;

        in = Cloud(bin,:);
        %%
        G = graph_creation(in, max_d);
        [comp,compsize]    = conncomp(G);
        comp(2,:) = compsize(1,comp(1,:));

        in.Cluster_Nr   =   comp(1,:)';
        in.Cluster_Size =   comp(2,:)';
        %%
        in.Cluster_Size(in.Cluster_Size < cluster_s)   = 0;
        in.Cluster_Nr(in.Cluster_Size < cluster_s)     = 0;

        Cloud(bin,:)    = in;
        Cluster_Nr      = Cloud.Cluster_Nr;
        Cluster_Size    = Cloud.Cluster_Size;
        %%
    end

    end    

