function choice = setup_dialog()
%% choice = setup_dialog() is the setup gui, subfuction of variable_setup()
%
% created by Manuel A. Luck (manuel.luck@gmail.com)

choice{24,3}    = [];
%% getting ScreenSize
    scrsz = get(0,'ScreenSize');
    
    width = floor(0.5 * scrsz(3));
    height = floor(0.9 .* scrsz(4));
    left = 1 + floor((scrsz(3) - width)/2);
    bottom = 1 + floor((scrsz(4) - height)/2);   
    
%%  Setup Windows   
    MainWindow = figure('Color','w','Position',[left bottom width height],...       % the main GUI figure
                        'HandleVisibility','callback', ...
                        'Name','Toolbox Setup', ...
                        'NumberTitle','off');
    
    Window1 = uipanel('Parent', MainWindow,'Title','General Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.01 .56 .24 .43]);  
                  
    Window2 = uipanel('Parent', MainWindow,'Title','DTM Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.01 .12 .24 .43]);   
                  
    Window3 = uipanel('Parent', MainWindow,'Title','Trunk Filtering Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.26 .56 .24 .43]);  
                  
    Window4 = uipanel('Parent', MainWindow,'Title','Trunk Clustering Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.26 .12 .24 .43]);  
                  
                  
    Window5 = uipanel('Parent', MainWindow,'Title','Crown Filtering Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.51 .56 .24 .43]);  
                  
    Window6 = uipanel('Parent', MainWindow,'Title','Tree Graph Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.51 .12 .24 .43]);                   
    
    Window7 = uipanel('Parent', MainWindow,'Title','Voxel Filter Setup',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.76 .56 .23 .43]);  
                  
    Window8 = uipanel('Parent', MainWindow,'Title','Patch Orientation',...
                      'ForegroundColor','k','FontSize',12,'FontWeight','bold',...
                      'BackgroundColor','white',...
                      'Units','normalized',...
                      'Position',[.76 .12 .23 .43]);
                  
%% Window1                   
    uicontrol('Parent',Window1,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Choose either fixed or interface setup.');
                
    general11 = uicontrol('Parent',Window1,...
                        'Style','popup',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String',{'interface';'fixed'},...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                  
    uicontrol('Parent',Window1,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.4 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Should the QSM of Raumonen et al. (2013) be used.');
                
    general12 = uicontrol('Parent',Window1,...
                        'Style','popup',...
                        'Units','normalized',...
                        'Position',[0.2 0.3 0.6 0.09],...
                        'String',{'no';'yes'},...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);  
                              
                
%% Window2                   
    uicontrol('Parent',Window2,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Choose how many iteration should be done in the DTM generation:');
                
    general21 = uicontrol('Parent',Window2,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String','10',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    uicontrol('Parent',Window2,...
                'Style','text',...
                'FontSize',10,...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.6 0.98 0.19],...
                'HorizontalAlignment','center',...
                'String',{'With each iteration the pointcloud is divided in 4 subclouds:';...
                          '1, 2x2, 4x4, 8x8, 16x16,...';...
                          '10 results in 1024x1024 cells'}); 
            
    uicontrol('Parent',Window2,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.4 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Choose the slopefactor:');
                
    general22 = uicontrol('Parent',Window2,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.3 0.6 0.09],...
                        'String','10',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);  
                    
    uicontrol('Parent',Window2,...
                'Style','text',...
                'FontSize',10,...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.1 0.98 0.19],...
                'HorizontalAlignment','center',...
                'String','A steeper terrain needs a higher slopefactor value.');
                  
%% Window3
    uicontrol('Parent',Window3,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Height Filter [m]:');
                
    general311 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.8 0.48 0.09],...
                        'String','3',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general312 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.8 0.48 0.09],...
                        'String','5',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);                    
                    
    uicontrol('Parent',Window3,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.7 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Easting [m]:');
                
    general321 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.6 0.48 0.09],...
                        'String','-9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general322 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.6 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window3,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.5 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Northing [m]:');
                
    general331 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.4 0.48 0.09],...
                        'String','-9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general332 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.4 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window3,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.3 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Intensity:');
                
    general341 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.2 0.48 0.09],...
                        'String','0.4',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general342 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.2 0.48 0.09],...
                        'String','1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window3,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.1 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Return Number:');
                
    general351 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.01 0.48 0.09],...
                        'String','0',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general352 = uicontrol('Parent',Window3,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.01 0.48 0.09],...
                        'String','11',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 

%% Window4
    uicontrol('Parent',Window4,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Maximal edgeweight [m]:');
                
    general41 = uicontrol('Parent',Window4,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String','0.25',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
                      
    uicontrol('Parent',Window4,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.7 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Directional weight x,y,z:');
                
    general421 = uicontrol('Parent',Window4,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.6 0.32 0.09],...
                        'String','1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general422 = uicontrol('Parent',Window4,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.34 0.6 0.32 0.09],...
                        'String','1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    general423 = uicontrol('Parent',Window4,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.67 0.6 0.32 0.09],...
                        'String','2',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);   
                    
    uicontrol('Parent',Window4,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.5 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Minimal cluster size:');
                
    general43 = uicontrol('Parent',Window4,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.4 0.6 0.09],...
                        'String','10',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                                       
%% Window5
    uicontrol('Parent',Window5,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Height Filter [m]:');
                
    general511 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.8 0.48 0.09],...
                        'String','1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general512 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.8 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);                    
                    
    uicontrol('Parent',Window5,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.7 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Easting [m]:');
                
    general521 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.6 0.48 0.09],...
                        'String','-9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general522 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.6 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window5,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.5 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Northing [m]:');
                
    general531 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.4 0.48 0.09],...
                        'String','-9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general532 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.4 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window5,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.3 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Intensity:');
                
    general541 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.2 0.48 0.09],...
                        'String','0.4',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general542 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.2 0.48 0.09],...
                        'String','1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window5,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.1 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Return Number:');
                
    general551 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.01 0.48 0.09],...
                        'String','0',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general552 = uicontrol('Parent',Window5,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.01 0.48 0.09],...
                        'String','11',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
%% Window6                   
    uicontrol('Parent',Window6,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Maximal edgeweight [m]:');
                
    general61 = uicontrol('Parent',Window6,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String','2',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                                                            
%% Window7                   
    uicontrol('Parent',Window7,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Should a voxel filter be applied on the Vegetation Points?');
                
    general71 = uicontrol('Parent',Window7,...
                        'Style','popup',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String',{'no';'yes'},...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                  
    uicontrol('Parent',Window7,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.7 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Choose the voxel height:');
                
    general72 = uicontrol('Parent',Window7,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.6 0.6 0.09],...
                        'String','0.1',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
    uicontrol('Parent',Window7,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.5 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Filtering voxel by amount of Points:');
            
    general731 = uicontrol('Parent',Window7,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.01 0.4 0.48 0.09],...
                        'String','0',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    general732 = uicontrol('Parent',Window7,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.51 0.4 0.48 0.09],...
                        'String','9999',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values); 
                    
%% Window8    
    uicontrol('Parent',Window8,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.9 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Include the surrounding Patches?');
                
    general83 = uicontrol('Parent',Window8,...
                        'Style','popup',...
                        'Units','normalized',...
                        'Position',[0.2 0.8 0.6 0.09],...
                        'String',{'no';'yes'},...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);
                    
    uicontrol('Parent',Window8,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.6 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Amount of Patches in Easting:');
                
    general81 = uicontrol('Parent',Window8,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.5 0.6 0.09],...
                        'String','14',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);    
                    
    uicontrol('Parent',Window8,...
                'Style','text',...
                'FontWeight','bold',...
                'BackgroundColor','white',...
                'Units','normalized',...
                'Position',[0.01 0.3 0.98 0.09],...
                'HorizontalAlignment','center',...
                'String','Amount of Patches in Northing:');
                
    general82 = uicontrol('Parent',Window8,...
                        'Style','edit',...
                        'Units','normalized',...
                        'Position',[0.2 0.2 0.6 0.09],...
                        'String','14',...
                        'HorizontalAlignment','center',...
                        'Callback',@refresh_values);   
                    
%% Close Figure Bottom       
    uicontrol('Parent',MainWindow,...
                'Units','normalized',...
                'Position',[0.4 0.05 0.2 0.05],...
                'String','Close',...
                'Callback','delete(gcf)');
                
%% Refresh Values                
    refresh_values();
    
%% Wait for figure to close before running to completion
    uiwait(MainWindow);
    
%% Functions   
       function refresh_values(arg1,arg2)
            % Window 1
            choice{1,1}   = general11.String(general11.Value);          
            choice{2,1}   = general12.String(general12.Value);
            
            % Window 2
            choice{3,1}   = general21.String;
            choice{4,1}   = general22.String;
            
            % Window 3
            choice{5,1}   = general311.String;
            choice{5,2}   = general312.String;
            choice{6,1}   = general321.String;
            choice{6,2}   = general322.String;
            choice{7,1}   = general331.String;
            choice{7,2}   = general332.String;
            choice{8,1}   = general341.String;
            choice{8,2}   = general342.String;
            choice{9,1}   = general351.String;
            choice{9,2}   = general352.String;
            
            % Window 4
            choice{10,1}  = general41.String;
            choice{11,1}  = general421.String;
            choice{11,2}  = general422.String;
            choice{11,3}  = general423.String;
            choice{12,1}  = general43.String;
            
            % Window 5
            choice{13,1}  = general511.String;
            choice{13,2}  = general512.String;
            choice{14,1}  = general521.String;
            choice{14,2}  = general522.String;
            choice{15,1}  = general531.String;
            choice{15,2}  = general532.String;
            choice{16,1}  = general541.String;
            choice{16,2}  = general542.String;
            choice{17,1}  = general551.String;
            choice{17,2}  = general552.String;
            
            % Window 6
            choice{18,1}  = general61.String;
            
            % Window 7
            choice{19,1}  = general71.String(general71.Value); 
            choice{20,1}  = general72.String;
            choice{21,1}  = general731.String;
            choice{21,2}  = general732.String;
            
            % Window 8
            choice{22,1}  = general81.String;            
            choice{23,1}  = general82.String;
            choice{24,1}  = general83.String(general83.Value); 
       end
   
end